"""Initial migration

Revision ID: 084fd4d31952
Revises: 
Create Date: 2026-08-05 23:10:26.568036

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '084fd4d31952'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_configs',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'parent_id', name='uq_category_name_parent')
    )
    op.create_table('email_sync_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_history_id', sa.String(), nullable=True),
    sa.Column('last_poll_at', sa.DateTime(), nullable=True),
    sa.Column('total_emails_processed', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('id = 1', name='chk_email_sync_state_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('total_spent', sa.Float(), nullable=False),
    sa.Column('total_income', sa.Float(), nullable=False),
    sa.Column('prev_month_spent', sa.Float(), nullable=True),
    sa.Column('prev_month_income', sa.Float(), nullable=True),
    sa.Column('spending_change_pct', sa.Float(), nullable=True),
    sa.Column('category_breakdown', sa.String(), nullable=True),
    sa.Column('weekly_trend', sa.String(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name='uq_monthly_report_year_month')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vpa', sa.String(), nullable=False),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vpa')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('vpa', sa.String(), nullable=True),
    sa.Column('merchant_name', sa.String(), nullable=True),
    sa.Column('raw_merchant_name', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('txn_ref', sa.String(), nullable=True),
    sa.Column('txn_type', sa.String(), nullable=False),
    sa.Column('account_last4', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('categorized_by', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('email_message_id', sa.String(), nullable=True),
    sa.Column('is_misclassified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txn_ref')
    )
    op.create_index('ix_transactions_category_id', 'transactions', ['category_id'], unique=False)
    op.create_index('ix_transactions_direction', 'transactions', ['direction'], unique=False)
    op.create_index('ix_transactions_email_message_id', 'transactions', ['email_message_id'], unique=False)
    op.create_index('ix_transactions_status', 'transactions', ['status'], unique=False)
    op.create_index('ix_transactions_timestamp_desc', 'transactions', [sa.literal_column('timestamp DESC')], unique=False)
    op.create_index('ix_transactions_txn_type', 'transactions', ['txn_type'], unique=False)
    op.create_index('ix_transactions_vpa', 'transactions', ['vpa'], unique=False)
    op.create_table('categorization_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('from_category_id', sa.Integer(), nullable=True),
    sa.Column('from_sub_category_id', sa.Integer(), nullable=True),
    sa.Column('to_category_id', sa.Integer(), nullable=False),
    sa.Column('to_sub_category_id', sa.Integer(), nullable=True),
    sa.Column('llm_response_raw', sa.String(), nullable=True),
    sa.Column('llm_inference_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['from_sub_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['to_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['to_sub_category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorization_logs')
    op.drop_index('ix_transactions_vpa', table_name='transactions')
    op.drop_index('ix_transactions_txn_type', table_name='transactions')
    op.drop_index('ix_transactions_timestamp_desc', table_name='transactions')
    op.drop_index('ix_transactions_status', table_name='transactions')
    op.drop_index('ix_transactions_email_message_id', table_name='transactions')
    op.drop_index('ix_transactions_direction', table_name='transactions')
    op.drop_index('ix_transactions_category_id', table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('sessions')
    op.drop_table('rules')
    op.drop_table('users')
    op.drop_table('monthly_reports')
    op.drop_table('email_sync_states')
    op.drop_table('categories')
    op.drop_table('app_configs')
    # ### end Alembic commands ###
